"""Type-only protocol used by mixins to share a static surface area.

Each mixin file inherits from ``_TaskServiceLike`` only under
``TYPE_CHECKING`` so the inheritance has no runtime effect — at runtime
the cross-mixin attributes resolve through ``TaskService``'s MRO. The
protocol lets pyright understand that ``self.scanner``, ``self._find_task``
etc. are valid lookups inside any mixin method.
"""
from __future__ import annotations

from pathlib import Path
from typing import Protocol

from ...locks import TaskLockManager
from ...metadata_store import MetadataStore
from ...models import (
    ChangedFileDetail,
    HumanLineComment,
    HumanReviewState,
    TaskContext,
    TaskMetadata,
    TaskStageTiming,
)
from ...scanner import KanbanScanner
from ...transitions import TransitionManager
from ._data import AssistantTokenUsageRow
from ..plan_approval_learning import PlanApprovalLearningService


class _TaskServiceLike(Protocol):
    """Static contract shared between the TaskService class and its mixins."""

    # Attributes set in TaskService.__init__
    scanner: KanbanScanner
    runs_root: Path
    kanban_root: Path
    archive_runs_root: Path
    metadata_store: MetadataStore | None
    transitions: TransitionManager | None
    locks: TaskLockManager | None
    plan_approval_learning: PlanApprovalLearningService

    # Methods defined in other mixins that may be called from siblings
    def _find_task(self, task_id: str) -> TaskContext: ...
    def _task_runs_dir(self, task_id: str) -> Path: ...
    def _validate_attachment_artifact(self, task, filename: str) -> Path: ...
    def _validate_readable_attachment(self, task_dir: Path, filename: str) -> Path: ...
    def _validate_readable_markdown_artifact(self, task_dir: Path, filename: str) -> Path: ...
    def _validate_writable_markdown_artifact(self, task_dir: Path, filename: str) -> Path: ...
    def _build_stage_timing(self, metadata: TaskMetadata) -> TaskStageTiming: ...
    def _build_human_review_state(self, task) -> HumanReviewState: ...
    def _format_duration_ms(self, duration_ms: int) -> str: ...
    def _summary_keywords(self, metadata: TaskMetadata) -> list[str]: ...
    def _target_repo_changed_files(self, metadata: TaskMetadata) -> list[ChangedFileDetail]: ...
    def _request_goal(self, task_dir: Path) -> str | None: ...
    def _artifact_summary(self, path: Path) -> str | None: ...
    def _latest_artifact_summary(self, task_dir: Path, pattern: str) -> str | None: ...
    def _parse_patch(self, patch_text: str) -> list[ChangedFileDetail]: ...
    def _resolve_patch_path(self, task_id: str, raw_path: str | None) -> Path | None: ...
    def _target_repo_diff_against_base(self, metadata: TaskMetadata, *, ref: str | None) -> str | None: ...
    def _load_current_cycle_line_comments(self, task, metadata: TaskMetadata) -> list[HumanLineComment]: ...
    def _load_all_line_comments(self, task, metadata: TaskMetadata) -> list[HumanLineComment]: ...
    def _assistant_token_usage_rows(self, task: TaskContext) -> list[AssistantTokenUsageRow]: ...
    def _format_token_total(self, total_tokens: int, unavailable_runs: int) -> str: ...
    def _markdown_table_cell(self, value: str) -> str: ...
    def _sorted_markdown_files(self, task_dir: Path) -> list[str]: ...
    def target_repo_summary_filename(self, metadata: TaskMetadata) -> str: ...
